# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e865bcf427ab1ec127972ffdc59753ae920337c79c6d4036ecea40152908522cfde5833e4b887a66bb3abe12ba107208e84dc19f3b929802a16cba72f07faddf

test:
  secret_key_base: 378852cab6e887fea7b4d92a514b7295f0570fb885c6f955991103aacb34fd1b429e4a9e372cfcd0ab86719643252b1da7c6c47bf0da29578bd1df9f21d18c31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
